//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEMS_Test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HEMS_testEntities : DbContext
    {
        public HEMS_testEntities()
            : base("name=HEMS_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
    
        public virtual int DeleteProduct(string code, ObjectParameter errN, ObjectParameter errM)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProduct", codeParameter, errN, errM);
        }
    
        public virtual int DeleteProductCategory(string code, ObjectParameter errN, ObjectParameter errM)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProductCategory", codeParameter, errN, errM);
        }
    
        public virtual int DeleteProductType(string code, ObjectParameter errN, ObjectParameter errM)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProductType", codeParameter, errN, errM);
        }
    
        public virtual int SaveProduct(ObjectParameter seq, string code, string product_category_code, string product_type_code, string name, string description, ObjectParameter errN, ObjectParameter errM)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var product_category_codeParameter = product_category_code != null ?
                new ObjectParameter("product_category_code", product_category_code) :
                new ObjectParameter("product_category_code", typeof(string));
    
            var product_type_codeParameter = product_type_code != null ?
                new ObjectParameter("product_type_code", product_type_code) :
                new ObjectParameter("product_type_code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveProduct", seq, codeParameter, product_category_codeParameter, product_type_codeParameter, nameParameter, descriptionParameter, errN, errM);
        }
    
        public virtual int SaveProductCategory(ObjectParameter seq, string code, string name, string description, ObjectParameter errN, ObjectParameter errM)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveProductCategory", seq, codeParameter, nameParameter, descriptionParameter, errN, errM);
        }
    
        public virtual int SaveProductType(ObjectParameter seq, string code, string product_category_code, string name, string description, ObjectParameter errN, ObjectParameter errM)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var product_category_codeParameter = product_category_code != null ?
                new ObjectParameter("product_category_code", product_category_code) :
                new ObjectParameter("product_category_code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveProductType", seq, codeParameter, product_category_codeParameter, nameParameter, descriptionParameter, errN, errM);
        }
    
        public virtual int SaveProductFull(string product_code, string product_name, string product_desc, string type_code, string type_name, string type_desc, string cat_code, string cat_name, string cat_desc, ObjectParameter errN, ObjectParameter errM)
        {
            var product_codeParameter = product_code != null ?
                new ObjectParameter("product_code", product_code) :
                new ObjectParameter("product_code", typeof(string));
    
            var product_nameParameter = product_name != null ?
                new ObjectParameter("product_name", product_name) :
                new ObjectParameter("product_name", typeof(string));
    
            var product_descParameter = product_desc != null ?
                new ObjectParameter("product_desc", product_desc) :
                new ObjectParameter("product_desc", typeof(string));
    
            var type_codeParameter = type_code != null ?
                new ObjectParameter("type_code", type_code) :
                new ObjectParameter("type_code", typeof(string));
    
            var type_nameParameter = type_name != null ?
                new ObjectParameter("type_name", type_name) :
                new ObjectParameter("type_name", typeof(string));
    
            var type_descParameter = type_desc != null ?
                new ObjectParameter("type_desc", type_desc) :
                new ObjectParameter("type_desc", typeof(string));
    
            var cat_codeParameter = cat_code != null ?
                new ObjectParameter("cat_code", cat_code) :
                new ObjectParameter("cat_code", typeof(string));
    
            var cat_nameParameter = cat_name != null ?
                new ObjectParameter("cat_name", cat_name) :
                new ObjectParameter("cat_name", typeof(string));
    
            var cat_descParameter = cat_desc != null ?
                new ObjectParameter("cat_desc", cat_desc) :
                new ObjectParameter("cat_desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveProductFull", product_codeParameter, product_nameParameter, product_descParameter, type_codeParameter, type_nameParameter, type_descParameter, cat_codeParameter, cat_nameParameter, cat_descParameter, errN, errM);
        }
    }
}
